// <auto-generated />
namespace PlanillaHorarios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Planilla_Observaciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Planilla_Observaciones));
        
        string IMigrationMetadata.Id
        {
            get { return "201608111523041_Planilla_Observaciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
