// <auto-generated />
namespace PlanillaHorarios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Planilla_anio_mes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Planilla_anio_mes));
        
        string IMigrationMetadata.Id
        {
            get { return "201608121209331_Planilla_anio_mes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
