// <auto-generated />
namespace PlanillaHorarios.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Estable01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Estable01));
        
        string IMigrationMetadata.Id
        {
            get { return "201701122037582_Estable01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
